### ISSUE TITLE
kubectl karmada  promote error: failed to get gvr from "extensions/v1beta1, Kind=Deployment"

### ISSUE THREAD

**Issue by zgfh** [karmada-io/karmada#1303]
**What happened**:
member cluster: k8s = 1.15.4: 
create test resouce: `kubectl create deployment test --image=daocloud.io/nginx --replicas=3`

Promote resouce to Karmada:
`kubectl karmada  promote deployment test -n default -c kind-kind-k8s-1-15`

error:
```
➜  ~ kubectl karmada  promote deployment test -n default -c kind-kind-k8s-1-15
Error: failed to get gvr from "extensions/v1beta1, Kind=Deployment": no matches for kind "Deployment" in version "extensions/v1beta1"
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
 
**Anything else we need to know?**:

**Environment**:
- Karmada version: 1.0.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): 1.0.0
- Others:  member cluster: k8s = 1.15.4:

**Comment by lonelyCZ** [comment]
Thank you pointed out. Could you please try below command?
```
kubectl karmada promote deployment.v1.apps test -n default -c kind-kind-k8s-1-15
```

I guess that is a compatibility problem of `apiVersion` of the `Deployment` in 1.15.4 k8s cluster.

**Comment by zgfh** [comment]
it work. thanks 

Is there any way to handle this automatically?

**Comment by lonelyCZ** [comment]
> it work. thanks

Thanks for testing it.

> Is there any way to handle this automatically?

I guess the reason is that the `api.Preference` of `Deployment` in `v1.15.4` k8s cluster is `extensions/v1beta1`, but in Karmada whose apiversion is `v1.21.7` and  `api.Preference` of `Deployment` is `apps/v1`, so cause this problem.

That is a compatibility problem of k8s apiversion, we need to find a way to fix it or a easy way that prompt users when the problem occurred.
