### ISSUE TITLE
Should we set registry and version variable in deploy-karmada.sh

### ISSUE THREAD

**Issue by wuyingjun-lucky** [karmada-io/karmada#1716]
**What would you like to be added**:
**Firstly**: As a green hand, I want to deploy karmada-control-plane in my k8s cluster;
**Secondly**: I make  the  karmada containers and download k8s core containers and push to my private registry because my k8s cluster can not connect the internet
**Thirdly**: I must modify the image written in the deploy yml 
**Why is this needed**:
**Firstly**:  It is not convenient 
Could we make the images and version variable just like the pic below then  replace the value in the deploy stage
<img width="899" alt="image" src="https://user-images.githubusercontent.com/16109961/166426154-9b6a4fa6-156c-49df-8374-44621eb98ed7.png">
So we can start a karmada control plane like 
<img width="934" alt="image" src="https://user-images.githubusercontent.com/16109961/166426384-3d2810a1-4b5b-4d5b-84c4-1c5f5e926b65.png">

**Comment by lonelyCZ** [comment]
Great, it's really easy to use using environment variables. We have implemented to replace image in `karmadactl init` command. It's a good idea to abstract out these values that can change, because I also encountered the situation that replaced multi images manually, like

https://github.com/karmada-io/karmada/blob/7b7ae06392e0952df51f0364671d27c12cd7faff/artifacts/deploy/kube-controller-manager.yaml#L55
