### ISSUE TITLE
The label value of the dependent resoucebinding over 63 characters

### ISSUE THREAD

**Issue by mathlsj** [karmada-io/karmada#1741]
The dependent resourcebinding label value consists of three components namspace+"_"+name+"-"+kind. it is easy to over 63 characters. we need to split it into three labels:
resourcebinding.karmada.io/depended-by-hash.namespace: namespace
resourcebinding.karmada.io/depended-by-hash.name: name
resourcebinding.karmada.io/depended-by-hash.kind: kind

**Comment by mathlsj** [comment]
generate resourcebinding depended label in  dependencies_distributor (https://github.com/karmada-io/karmada/blob/master/pkg/dependenciesdistributor/dependencies_distributor.go)

```
func generateBindingDependedByLabel(bindingNamespace, bindingName string) map[string]string {
	labelKey := generateBindingDependedByLabelKey(bindingNamespace, bindingName)
        # labelValue = ns +"_" + bindingName (name + "-" + kind)
	labelValue := fmt.Sprintf(bindingNamespace + "_" + bindingName)
	return map[string]string{labelKey: labelValue}
}
```

**Comment by RainbowMango** [comment]
Right, here probably exceed 64 characters. May I know what the `name` and `namespace` look like in your system?

**Comment by RainbowMango** [comment]
Hi @mathlsj I see you send a PR for this. 
I'd like to invite the author to talk about the solution. @mrlihanbo

**Comment by mathlsj** [comment]
OK。

**Comment by mathlsj** [comment]
@RainbowMango What is the progress of this?

**Comment by RainbowMango** [comment]
I'm sorry I missed this from my radar. I'll be back on this next week.

**Comment by RainbowMango** [comment]
> Right, here probably exceed 64 characters. May I know what the `name` and `namespace` look like in your system?

@mathlsj Can you give an example of your `name` and `namespace`?

**Comment by RainbowMango** [comment]
> we need to split it into three labels:
resourcebinding.karmada.io/depended-by-hash.namespace: namespace
resourcebinding.karmada.io/depended-by-hash.name: name
resourcebinding.karmada.io/depended-by-hash.kind: kind

Split the label could relieve the issue, but I'm afraid it can't solve the problem fundamentally, because the `name` itself may exceed 63 characters.

Investigation still on-going.

**Comment by RainbowMango** [comment]
I've got two solutions here:
1. Instead of putting the key `resourcebinding.karmada.io/depended-by-xxx` to a label, we can put it in the `annotations`.

For doing this, we can't use the `label selector` to list all the dependencies at [listAttachedBindings](https://github.com/karmada-io/karmada/blob/afa766117e94ecc0603fc02174965ca514fefe3c/pkg/dependenciesdistributor/dependencies_distributor.go#L475), maybe we can use [MatchingFieldsSelector](https://github.com/kubernetes-sigs/controller-runtime/blob/e2b265bf7879ae9d1faa66f0503b09c4bb83eb72/pkg/client/options.go#L549).

2. Deprecate the key by extending the ResourceBinding API to build the connection between `main` RB and attached `RB`s.

I didn't verify any of the two solutions yet, just an idea.

**Comment by mathlsj** [comment]
I tend to use the first one.

I was thinking if there was any other solution to it?

**Comment by RainbowMango** [comment]
> I was thinking if there was any other solution to it?

Looking forward to hear more solutions.
My concern about the two solutions is the performance, you know there could be a huge mount of RBs in the system.

**Comment by mathlsj** [comment]
I am sorry. i was so busy before. i will deal it continue.

**Comment by RainbowMango** [comment]
@XiShanYongYe-Chang Can you confirm if this issue is fixed?

**Comment by XiShanYongYe-Chang** [comment]
The current issue has not been resolved. This is a separate label. This label is not analyzed in #4000. I will use [this idea](https://github.com/karmada-io/karmada/issues/1741#issuecomment-1436540337) and the resolution experience in #4000 to continue to promote this issue.

/assign

**Comment by XiShanYongYe-Chang** [comment]
Hi @mathlsj, this issue has been solved, would you like to have a try?
