### ISSUE TITLE
Use remote-up-karmada.sh install karmada in kind

### ISSUE THREAD

**Issue by calvin0327** [karmada-io/karmada#1816]
**What happened**:
After installing karmada in the kind cluster.  the karmada-apiserver failed to conenct.

I cat the `~/.kube/config` and find the new cluster server be added. but the url can't be access on the host.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/45745657/168840322-67e88528-caec-4d1c-9c19-c7619ef526e6.png">

<img width="658" alt="image" src="https://user-images.githubusercontent.com/45745657/168840519-debfee2b-19d0-4e1f-9c08-340e4be55acd.png">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
exec remote-up-karmada.sh on your host and have a kind cluster.

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
Seems the service of `karmada-apiserver` hasn't been exposed. 
It is not recommended to install Karmada on a kind cluster by `hack/remote-up-karmada.sh`, it's not convenient since you might have to consider how to expose the service. [See the comments](https://github.com/karmada-io/karmada/blob/be5755daaf287b5618b8c86844e0a6f034f5b733/hack/remote-up-karmada.sh#L13).

Why not use `hack/local-up-karmada.sh` if you just want to try Karmada, or `karmadactl init`?
For more details about the installation, please refer to [installation guide](https://github.com/karmada-io/karmada/blob/master/docs/installation/installation.md).

**Comment by calvin0327** [comment]
@RainbowMango thanks.  It's really convenient to exec `local-up-karmada.sh` to install karmada.

**Comment by RainbowMango** [comment]
Thanks for the feedback.

/close
I guess we can close it now.
