### ISSUE TITLE
How to support failover when member clusters status is unknow?

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#2096]
**Please provide an in-depth description of the question you have**:

Currently, we support failover when member cluster is unjoined. But sometime, we can't predict cluster failure. If the cluster has been UnKnown for a period of time, how to trigger failover.

Like below logs, the cluster was unknown over 1 hour, but not to trigger rescheduler.
```
I0630 12:43:12.260426       1 cluster_controller.go:453] cluster member140 hasn't been updated for 1h11m46.338303374s. Last Ready is: &Condition{Type:Ready,Status:Unknown,ObservedGeneration:0,LastTransitionTime:2022-06-30 11:32:06 +0000 UTC,Reason:ClusterStatusUnknown,Message:Cluster status controller stopped posting cluster status.,}
```

**What do you think about this question?**:

In most scenarios, after a cluster has been UnKnown for a period of time, it is possible that the cluster has failed and we need to trigger rescheduling.

**Environment**:
- Karmada version: v1.2.0
- Kubernetes version: v1.22.9
- Others:

**Comment by prodanlabs** [comment]
It seems to me that the member clusters status is `NotReady` or `Unknown`, it is possible that the network or member clusters master node sent a failure, which does not mean that the workload is unavailable.

Secondly, if it is `NotReady` or `Unknown` due to network instability at a certain point in time, it is unreasonable to trigger rescheduling.

> In most scenarios, after a cluster has been UnKnown for a period of time, it is possible that the cluster has failed and we need to trigger rescheduling.

Agree, but we should provide some strategies or options for users to choose, such as how long the NotReady or unknown state lasts to trigger the rescheduling, 10m, 30m....

**Comment by lonelyCZ** [comment]
@prodanlabs Thanks for your share!

> Agree, but we should provide some strategies or options for users to choose, such as how long the NotReady or unknown state lasts to trigger the rescheduling, 10m, 30m....

Yes, it will be very useful.

**Comment by XiShanYongYe-Chang** [comment]
As a lack of activity, let's close this first, feel free to reopen it if you still need it.
/close
