### ISSUE TITLE
Member cluster job is rebuilt unexpectedly

### ISSUE THREAD

**Issue by 1285yvonne** [karmada-io/karmada#2197]
**What happened**:  We have enabled the ttl-after-finished controller in the karmada control plane to help users delete redundant jobs. At the meantime, member clusters have enabled this controller too. So when the job were deleted by member clusters, karmada-agent create a new one immediately and will update job's status in the host cluster. Therefore this job will never be deleted by karmada-kube-controller-manager and will always be rebuilt  unexpectedly.

**What you expected to happen**:  If the Job'status has been updated to `Completed` or `Failed`, the execution-controller should not recreate Job in member cluster.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: Our temporary approach is not propagating `job.Spec.TTLSecondsAfterFinished` field. 

**Environment**:
- Karmada version: v1.0.2
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by Alphonse-iwnl** [comment]
it easy to repro in `v1.0.2` if member cluster open `TTLAfterFinished` feature. 

once `job.Spec.TTLSecondsAfterFinished` has configured,  job in member cluster would recycle by ttl controller, meanwhile  `workStatusController` will recreate the job because job in control plane has not recycle yet, after recreate, new job's status would sync to the job in control-plane, which prolong the finished time of job in control-plane and it will never trigger ttl recycle.

i noticed it has improve in `v1.2` for  `aggregateJobStatus` stoping update finish condition.lastTransitionTime if job had finished, it would help job in control-plane recycle correctly by ttl controller, but it cant stop job in member cluster recreate by workStatusController if job in member cluster has an earlier finshed time than the job in control plane(so it would recreate before job in control-plane has recycle).

anyway, i thought the key point of these question is: lifecycle management for job in member cluster should be performed by karmada-contol-plane instead of ttl controller(in member cluster),  `job.Spec.TTLSecondsAfterFinished` maybe disturb it. therefore i have 2 suggestion for handle this:

- delete `job.Spec.TTLSecondsAfterFinished` in propagating (by interpreter or webhook)
- stop recreate finished job in workStatusController

**Comment by RainbowMango** [comment]
I  nearly missed this interesting use case, and thanks @Alphonse-iwnl for the excellent analysis and suggestions.

> We have enabled the ttl-after-finished controller in the karmada control plane to help users delete redundant jobs. At the meantime, member clusters have enabled this controller too. 

In the case of both the Karmada control plane and member clusters enabled `TTL-after-finished` controller, obviously, the member cluster would do the cleanup thing sooner than the Karmada control plane. 

@Garrybest Have you ever met this issue?

**Comment by Garrybest** [comment]
Thanks @Alphonse-iwnl, I truely agree with you. We should let karmada do all cleanup jobs. So if ttl-after-finished controller is enabled, we'd better not propagate `job.spec.ttlSecondsAfterFinished`.

Since we already find out the causes, would you like to contribute a patch? 😄

**Comment by chaunceyjiang** [comment]
> we'd better not propagate job.spec.ttlSecondsAfterFinished

https://github.com/karmada-io/karmada/blob/df125af3b0504c5a6b11d67ac68b6de577baa454/pkg/resourceinterpreter/defaultinterpreter/prune/prune.go#L59-L68


I think we can remove it here.

**Comment by RainbowMango** [comment]
> We should let karmada do all cleanup jobs. So if ttl-after-finished controller is enabled, we'd better not propagate job.spec.ttlSecondsAfterFinished.

+1 I agree that should let Karmada manage the Job lifecycle, actually more than Job, this applies to all resources.

The thing is how do we know the `ttl-after-finished` controller is enabled on the control plane? we can't just remove/prune the `job.Spec.TTLSecondsAfterFinished`.

**Comment by chaunceyjiang** [comment]
> The thing is how do we know the ttl-after-finished controller is enabled on the control plane? 

Do you mean that if the `ttl-after-finished` controller  is disabled on in the control plane, then `job.Spec.TTLSecondsAfterFinished` still needs to be propagated to member clusters?

**Comment by RainbowMango** [comment]
> Do you mean that if the ttl-after-finished controller is disabled on in the control plane, then job.Spec.TTLSecondsAfterFinished still needs to be propagated to member clusters?

No really. I mean we can't make the decision for users, especially they might don't know about it.  Otherwise, they will be surprised.

**Comment by 1285yvonne** [comment]
If a Job'status has been updated to Completed or Failed, the karmada-agent or karmada-controller-manager should not recreate this Job in member clusters.

Actully I think it is a better choice to avoid recreating that Job.

**Comment by Alphonse-iwnl** [comment]
> > We should let karmada do all cleanup jobs. So if ttl-after-finished controller is enabled, we'd better not propagate job.spec.ttlSecondsAfterFinished.
> 
> +1 I agree that should let Karmada manage the Job lifecycle, actually more than Job, this applies to all resources.
> 
> The thing is how do we know the `ttl-after-finished` controller is enabled on the control plane? we can't just remove/prune the `job.Spec.TTLSecondsAfterFinished`.


i thought its reasonable to remove`job.Spec.TTLSecondsAfterFinished`.

if ttl controller is disable in control plane, job in control plane would not recycle automatically, in the case if `TTLSecondsAfterFinished` has propagated, job in member cluster might rebuilt unexpectedly just like [1285yvonne](https://github.com/1285yvonne) told.

if ttl controller is enable in control plane, configuring `TTLSecondsAfterFinished ` does not make sense for jobs in member clusters, because we hope job in member cluster recycled by karmada control plane. in the case, even though job in member cluster didnt configured `TTLSecondsAfterFinished`, it would be deleted when the job in control plane had cleanup by ttl controller.

back to user cases, user config `TTLSecondsAfterFinished ` for cleanup the finished job. For karmada managed resource, either user choice clean them all, or keep them all, and we can guarantee this without propagating `TTLSecondsAfterFinished ` to member cluster's jobs.

**Comment by chaunceyjiang** [comment]
So do we need to delete `TTLSecondsAfterFinished ` this field?

@RainbowMango @Garrybest @Alphonse-iwnl 

If necessary, I can help delete it.

**Comment by Garrybest** [comment]
IMO, I prefer not propagating this filed.
