### ISSUE TITLE
How to set up karmada across Cloud Service Provider?

### ISSUE THREAD

**Issue by chenliu1993** [karmada-io/karmada#2246]
**Please provide an in-depth description of the question you have**:
Is there a guide about how to set up the karmada across multiple cloud? 
Like setting up one kind cluster as apiserver in TencentCloud while have one three-node kubernetes cluster as worker cluster in Huawei Cloud?
**What do you think about this question?**:

**Environment**:
- Karmada version: latest
- Kubernetes version: 1.24
- Others:  kind version v0.14
- OS: CentOS 8.6

**Comment by RainbowMango** [comment]
> Like setting up one kind cluster as apiserver in TencentCloud while have one three-node kubernetes cluster as worker cluster in Huawei Cloud?

Do you mean to set up the Karmada control plane in `TencentCloud` and let Karmada manages clusters in `Huawei Cloud`?

**Comment by chenliu1993** [comment]
> > Like setting up one kind cluster as apiserver in TencentCloud while have one three-node kubernetes cluster as worker cluster in Huawei Cloud?
> 
> Do you mean to set up the Karmada control plane in `TencentCloud` and let Karmada manages clusters in `Huawei Cloud`?

Yes.
Actually, it is a little bit more complicated. Like set cp in TencentCloud in the form of a kind cluster. And Huawei Cloud's cluster is managed by this kind cluster.
But I think if I can get one answer like you mentioned in the comment is also good enough for me, too.

**Comment by RainbowMango** [comment]
> Like set cp in TencentCloud in the form of a kind cluster. 

What's the `cp` thing? 
But, I'm surprised that you are using a `kind cluster` to install the Karmada control plane(ignore me if you are using it for testing purposes), because kind is not for production cases. 

For your question, actually Karmada don't care where the cluster is, no matter from another provider or your priviate cloud, as long as Karmada can talk to it. You might need to take care of the network issues.

**Comment by chenliu1993** [comment]
Thanks for the answer！let me try to make the network accessible.
