### ISSUE TITLE
Can not see the unsuccess pod when talk with karamda control plane

### ISSUE THREAD

**Issue by vincent-pli** [karmada-io/karmada#301]
**What would you like to be added**:
I'm new for the `karmada` and take a try with the quick start. 
Everything works well but the final `deployment` is not work as expect, I mean the relevant `pod` not start.

I have no idea what I missing until I talk to `member1` control plane directly, and the pod with `ImagePullBackOff` since the docker hub's rate limited.

**Why is this needed**:
I don't know, maybe it's by design, but I guess it's should be better that user can know what happen with `karamda` control plane

**Comment by RainbowMango** [comment]
> Everything works well but the final deployment is not work as expect, I mean the relevant pod not start.

Yes, it works as expected. The `deployment` deployed to `karmada` control plane will not create pods or replicaset because there is no relevant controllers deployed, such as `deployment` controller.

Actually, the `karmada` control plane only holds the resource template but not really run it unless you also deploy at least one policy, such as PropogationPolicy.

**Comment by RainbowMango** [comment]
> I have no idea what I missing until I talk to member1 control plane directly, and the pod with ImagePullBackOff since the docker hub's rate limited.

Sorry, I misunderstand you. Do you mean the deployment can't work at `member1` cluster?

**Comment by vincent-pli** [comment]
@RainbowMango 
No, you understand correct, please feel free to close the issue.

**Comment by RainbowMango** [comment]
OK then.
