### ISSUE TITLE
Support modification synchronization of custom resources as dependency

### ISSUE THREAD

**Issue by whitewindmills** [karmada-io/karmada#3605]
**What would you like to be added**:
Current `InterpretDependency` supports custom implementations to interpret the dependencies be propagated together. But, when the custom resource is modified, only built-in resources, like `configmaps`, `secrets`, `serviceaccounts` and `persistentvolumeclaims` , can be automatically propagated.

karmada's
![image](https://github.com/karmada-io/karmada/assets/89241565/5806b2b0-3aee-4024-8f90-36e60b7c9252)

member's
![image](https://github.com/karmada-io/karmada/assets/89241565/cb248ac8-d54b-40ec-bdee-b4328c85f024)

**Why is this needed**:
Any resources propagated through _Karmada_ should support be automatically propagated when some fields changed.

**Comment by whitewindmills** [comment]
@yike21 Hi
I guess you did not get me. This custom resource was propagated as dependency rather than individually.

**Comment by RainbowMango** [comment]
@yike21 
I think the root cause is that `dependencies-distributor` now only watches a limited `supported types`(including [configmaps/secrets/serviceaccounts/persistentvolumeclaims](https://github.com/karmada-io/karmada/blob/9bac51dbdf29ac0c564d47a96f4eeb13fe85e91f/pkg/dependenciesdistributor/dependencies_distributor.go#L50-L55)), these resource changes will be synced automatically, but for other resources like customized by `resource interpreter`(https://github.com/karmada-io/karmada/blob/9bac51dbdf29ac0c564d47a96f4eeb13fe85e91f/pkg/dependenciesdistributor/dependencies_distributor.go#L339), the changes will not be synced (I can't see the Kind from the issue description, but I guess it should be a CRD, or at least not on the supported list).

@whitewindmills @chaunceyjiang Please correct me if not the case.

**Comment by chaunceyjiang** [comment]
> , but for other resources like customized by resource interpreter , the changes will not be synced .



Yes,  [This PR ](https://github.com/karmada-io/karmada/pull/2524 )can help you better understand. When I added SA before, I forgot to add it to the support list of dependencies-distributor.  the SA changes will not be synced to member clusters.

**Comment by yike21** [comment]
Thank you for clearing up the confusion. @whitewindmills @RainbowMango @chaunceyjiang
