### ISSUE TITLE
In push mode, a member cluster should not join multiple karmada host clusters at the same time

### ISSUE THREAD

**Issue by yanfeng1992** [karmada-io/karmada#3678]
**What happened**:

I have two host clusters, hostcluster1, hostcluster2,   one member cluster membercluster1

step1: I found that in push mode, membercluster1 can join hostcluster1 and hostcluster2 at the same time, and the member cluster membercluster1 status is true

Step2: When I unjoin  membercluster1 on any host cluster, the status of member membercluster1 in another host cluster becomes false

**What you expected to happen**:

A cluster can only be added to one host cluster

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:  v1.5.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
I think Karmada supports registering the same cluster to multiple Karmada control planes.
But I don't know what's going on here when `unjoin` the cluster from one of the Karmada control planes.
Could you please tell us how to reproduce it?

**Comment by whitewindmills** [comment]
If we provide cluster kubeconfig, cluster role, cluster rolebinding and service account will be deleted from the unjoining cluster  
so that other host clusters will not be able to access this member cluster normally. If we do not provide cluster kubeconfig, all is well.
But Should we supports registering the same cluster to multiple Karmada control planes? If we do support it, the same resources which are propagated from the different host clusters will conflict with each other, that will cause some catastrophic problems.

**Comment by RainbowMango** [comment]
> But Should we supports registering the same cluster to multiple Karmada control planes? If we do support it, the same resources which are propagated from the different host clusters will conflict with each other, that will cause some catastrophic problems.

I'm saying that Karmada might support this from a technical perspective. But I don't know if there is a real use case. 
So, the question is why do you want to register a cluster to multiple control planes?

**Comment by RainbowMango** [comment]
> The kamada operator developed by our team can support the cluster join function in push mode. In our karmada-operator, we can check whether the member cluster has been joined. Use a cr to indicate the role of the current cluster, such as standalone, host, member, hostplusmember. Maybe the karmada community can refer to this idea?

As I mentioned above, I hope to hear your usage scenarios and see if it is a reasonable feature.

**Comment by whitewindmills** [comment]
> As I mentioned above, I hope to hear your usage scenarios and see if it is a reasonable feature.

No, We do have such usage scenario,
> I'm saying that Karmada might support this from a technical perspective

instead we just consider this behavior to be a bug.

Some guys may inadvertently register the same cluster to multiple control planes, which will cause some conflicts, so we hope to prohibit this behavior.

**Comment by RainbowMango** [comment]
> Some guys may inadvertently register the same cluster to multiple control planes, which will cause some conflicts, so we hope to prohibit this behavior.

I just remembered that we will query the UUID of the `kube-system` from the member cluster when joining a cluster, and take the ID as a unique ID. If the same cluster tries to register again, even with another name, the operation will be rejected. 
https://github.com/karmada-io/karmada/blob/9bac51dbdf29ac0c564d47a96f4eeb13fe85e91f/pkg/karmadactl/join/join.go#L176-L184

Sorry for the misleading answers above.

**Comment by yanfeng1992** [comment]
> > Some guys may inadvertently register the same cluster to multiple control planes, which will cause some conflicts, so we hope to prohibit this behavior.
> 
> I just remembered that we will query the UUID of the `kube-system` from the member cluster when joining a cluster, and take the ID as a unique ID. If the same cluster tries to register again, even with another name, the operation will be rejected.
> 

The problem is registering the same cluster to multiple Karmada control planes, not registering the same cluster to the same Karmada control plane. 

Please allow me to explain this problem again. It is not is a real use case to register the same cluster to multiple Karmada control planes, but a human error. When I unjoin on a karmada plane (karmada controllerplane A) this cluster(member1 ) to solve this problem, the cluster (member1) in another karmada control plane (karmada controllerplane B) is also affected.

**Comment by RainbowMango** [comment]
Yeah. I got it. Thanks for the reminder. 

Given the use case is not clear for now, I think we can postpone it for a while.

> Some guys may inadvertently register the same cluster to multiple control planes, which will cause some conflicts, so we hope to prohibit this behavior.

For this concern, if can do something if the solution is simple enough, however, if the changes are significant, we can postpone it.

**Comment by diegoyanezbastidas** [comment]
I am trying to federate three Minikube clusters on a single instance using Karmada, but I encounter several problems:

Issues with Pull Mode:

Duplicate certificate error in /var/lib/karmada/pki.
Deleting certificates is not viable as it affects the control plane.
Push Mode Restrictions:

Cannot use push mode because it would convert clusters to control plane, which Karmada prohibits.
External Cluster Joining:

Bootstrap token error despite being authorized.
Known issue in Karmada without a solution yet.
Demonstration Difficulties:

The above problems prevent effective setup and demonstration.
Community script usage also fails due to bootstrap token errors.
These issues make it challenging to present Karmada as a viable solution for cluster federation in a production environment.

**Comment by RainbowMango** [comment]
@diegoyanezbastidas I can't identify what's going on in your case, is there anything similar to this issue?
