### ISSUE TITLE
Cherrypick #4144: fix cannot access ResourceRegistry with its singularName

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#4152]
**Which PR needs cherry-picks:**

PR #4144 

**Which release branches need this patch:**

- [x] release-1.7 #4153 
- [x] release-1.6 #4157 
- [x] release-1.5 #4155

**How to cherry-pick PRs:**

The `hack/cherry_pick_pull.sh` script can help you initiate a cherry-pick
automatically, please follow the instructions at [this guideline](https://karmada.io/docs/contributor/cherry-picks). 

The script will send the PR for you, please remember `copy the release notes` from
the original PR by to the new PR description part.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a **separate line**.

Then, the issue will be assigned to you.

**Useful References:**

- Release timeline: https://karmada.io/docs/releases
- How to cherry-pick PRs: https://karmada.io/docs/contributor/cherry-picks

**Anything else we need to know:**

**Comment by RainbowMango** [comment]
@XiShanYongYe-Chang 
release-1.5 and release-1.6 aren't affected by this bug. (I tested against v1.5.4, there is no problem.)

This bug was introduced by #3730 when we updated Kubernetes dependencies to v1.27. So, we only need to fix it at `release-1.7` and `master`.

There is no side-effect checking them to release-1.5 and release-1.6 though.

**Comment by XiShanYongYe-Chang** [comment]
@RainbowMango Ok, thanks

> This bug was introduced by #3730

I'd like to know how this is confirmed.
