### ISSUE TITLE
get kubeconfig

### ISSUE THREAD

**Issue by zxyyy0119** [karmada-io/karmada#4172]
Is there a way for me to get managed cluster's kubeconfig from hub cluster?

**Comment by RainbowMango** [comment]
I guess `the managed cluster` is the member cluster that is registered in Karmada.

Do you mean to get the member cluster's kubeconfig from the Karmada control plane?
Why would you do that?

**Comment by zxyyy0119** [comment]
Do you mean to get the member cluster's kubeconfig from the Karmada control plane?
Yes.
Why would you do that?
After obtaining the member cluster's kubeconfig from the Karmada control plane, we would like to use it to access and mange the managed cluster's information.

**Comment by RainbowMango** [comment]
> After obtaining the member cluster's kubeconfig from the Karmada control plane, we would like to use it to access and mange the managed cluster's information.

It's not recommended to use the kubeconfig stored in the Karmada control plane, as the kubeconfig is generated during a member cluster and is dedicated to Karmada. It may not have enough permissions you need, on the other hand, if you use this Kubeconfig it would corrupt the audit log, since from a member cluster perspective, all instructions comes from Karmada.

Actually, you manipulate member clusters by Karmada, see [Aggregated Kubernetes API Endpoint](https://karmada.io/docs/next/userguide/globalview/aggregated-api-endpoint/) for more details. This feature is integrated into `karmadactl`, you can have a try with it.
