### ISSUE TITLE
Restrict “configmap/extension-apiserver-authentication” object from being distributed to member clusters.

### ISSUE THREAD

**Issue by Rong-Fang** [karmada-io/karmada#4228]
**What would you like to be added**:
While implementing Karmada to support the distribution of resources under the "kube-system" namespace, the "configmap/extension-apiserver-authentication" object created by kube-apiserver will not be distributed to member clusters.

**Why is this needed**:
Since Karmada uses the "skipped-propagating-namespaces" configuration item to control the distribution of resources, this configuration item prevents users from distributing resources to namespaces starting with "kube-*". Users can modify this configuration item to distribute resources under the "kube-system" namespace. However, when this configuration item is modified, the "configmap/extension-apiserver-authentication" object previously created by kube-apiserver will be distributed to the member clusters. Therefore, one method should be provided to allow users to distribute resources under “kube-system“ namespace, while the "configmap/extension-apiserver-authentication" object remains under the kube-system namespace.

**Comment by RainbowMango** [comment]
The `configmap/extension-apiserver-authentication` is generated and managed by `cluster-authentication-info-controller` in `kube-apiserver`.
https://github.com/kubernetes/kubernetes/blob/36930f4cb605450ccbe3126caad365aa5f51267c/pkg/controlplane/controller/clusterauthenticationtrust/cluster_authentication_trust_controller.go#L136-L175

Since both namespace and namespace are hardcoded, we can't change it. (this is another side effect of using kube-apiserver :( ).

**Comment by RainbowMango** [comment]
As a short-term solution, I suggest ignoring the `configmap/extension-apiserver-authentication` in the detector, like:
```diff
diff --git a/pkg/detector/detector.go b/pkg/detector/detector.go
index 62d40fd4f..a34768273 100644
--- a/pkg/detector/detector.go
+++ b/pkg/detector/detector.go
@@ -233,16 +233,15 @@ func (d *ResourceDetector) Reconcile(key util.QueueKey) error {
        return d.propagateResource(object, clusterWideKey)
 }

-// EventFilter tells if an object should be take care of.
+// EventFilter tells if an object should be taken care of.
 //
-// All objects under Kubernetes reserved namespace should be ignored:
-// - kube-*
 // All objects under Karmada reserved namespace should be ignored:
 // - karmada-system
 // - karmada-cluster
 // - karmada-es-*
 //
-// If '--skipped-propagating-namespaces' is specified, all APIs in the skipped-propagating-namespaces will be ignored.
+// If '--skipped-propagating-namespaces'(defaults to kube-.*) is specified,
+// all resources in the skipped-propagating-namespaces will be ignored.
 func (d *ResourceDetector) EventFilter(obj interface{}) bool {
        key, err := ClusterWideKeyFunc(obj)
        if err != nil {
@@ -279,6 +278,14 @@ func (d *ResourceDetector) EventFilter(obj interface{}) bool {
                }
        }

+       // Prevent configmap/extension-apiserver-authentication from propagating as it is generated
+       // and managed by kube-apiserver.
+       // Refer to https://github.com/karmada-io/karmada/issues/4228 for more details.
+       if clusterWideKey.Namespace == "kube-system" && clusterWideKey.Kind == "ConfigMap" &&
+               clusterWideKey.Name == "extension-apiserver-authentication" {
+               return false
+       }
+
        return true
 }
```
cc @chaunceyjiang @GitHubxsy for comments.

**Comment by RainbowMango** [comment]
This issue reminds me that we might consider introducing a feature that lets people decide which resources should be ignored, for example:
1. Users can label a specific resource to indicate the resource should be ignored.
   * for instance, by a new introduced-label `resourcetemplate.karmada.io/skip-propagation: true`, so that the detector can ignore the resource automatically.
2. Users can declare a ignore list or exception list in resource selector of a `PropagationPolicy`.
For instance:
```yaml
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: ConfigMap
      namespace: kube-system
      excludes:
        - extension-apiserver-authentication  // excludes specific resource 
```

**Comment by chaunceyjiang** [comment]
I believe we shouldn't hard code here. If users choose to reuse the existing `kube-apiserver`, this hard coding might cause other problems.

**Comment by RainbowMango** [comment]
The above ugly logic is a tradeoff, it will be there until we have our own apiserver.

**Comment by RainbowMango** [comment]
> Users can modify this configuration item to distribute resources under the "kube-system" namespace. However, when this configuration item is modified, the "configmap/extension-apiserver-authentication" object previously created by kube-apiserver will be distributed to the member clusters.

@Rong-Fang Do you configured the [conflictResolution](https://github.com/karmada-io/karmada/blob/d73e47bb1d277a4a34296ab2d6cd379dc9963282/pkg/apis/policy/v1alpha1/propagation_types.go#L138C47-L138C65)?
If not, or specify `conflictResolution: Abort`, actually the configmap won't be ultimately propagated to the member cluster, because Karmada will abort the propagation instead of overwrite the one in member cluster.
The error log is as follows:
```
E1115 06:42:27.747660       1 execution_controller.go:201] Failed to create or update resource(kube-system/extension-apiserver-authentication) in the given member cluster member2, err is resource(kind=ConfigMap, kube-system/extension-apiserver-authentication) already exist in cluster member2 and the work.karmada.io/conflict-resolution strategy value is empty, karmada will not manage this resource
```

PS: 
I'm saying that because I want to clarify the impact of this issue.
I thought that if the user enabled `kube-system` terrible things would happen, but now it seems that it won't. That's a relief.

**Comment by Rong-Fang** [comment]
Yes, the user has set "conflictResolution" to "Overwrite" type.
