### ISSUE TITLE
Support smooth cluster switching of Pods after PP changes

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#4417]
**What would you like to be added**:
After PP is changed, I want the new pods to be ready before deleting the pods in the old clusters.

**Why is this needed**:
There is the following scenario:
First, I propagate deployment to member1,
then, I modified PP to propagate deployment to member2.

In this scenario, the pod creation in member2 and the pod deletion in member1 is proceed simultaneously.
If the deletion is faster and the creation is slower, the service may fail.

**Comment by watermeion** [comment]
In our scenario, it's essential to regularly adjust replica weights across clusters due to cost optimization considerations.

Coupled with this, it's noted that in some cases, the duration for a pod to transition into a ready state can be substantially long.
there will definitely be service disruptions after  pp changes.

**Comment by RainbowMango** [comment]
The proposal in #4773 tracks this feature.
/close
cc @chaosi-zju
