### ISSUE TITLE
[Umbrella] Open component imagePullPolicy setting parameters for karmadactl init and karmada operator

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#4789]
**What would you like to be added**:

Open component `imagePullPolicy` setting parameters for `karmadactl init` and `karmada operator`.

- [x] open component `imagePullPolicy` setting parameters for `karmadactl init`. @XiShanYongYe-Chang #4815 
- [x] open component `imagePullPolicy` setting parameters for `karmada operator`. @seanlaii #4863 

**Why is this needed**:

The helm installation method already provides users with the ability to set the component imagePullPolicy parameters:

https://github.com/karmada-io/karmada/blob/c81649a423165bd660a3bf0ee3b1abd13b0f90e3/charts/karmada/values.yaml#L28-L30

https://github.com/karmada-io/karmada/blob/c81649a423165bd660a3bf0ee3b1abd13b0f90e3/charts/karmada/values.yaml#L175

In order to ensure the consistency of different installation methods and users can customize the image pull strategy of the Karmada component, we can also provide `imagePullPolicy` parameter settings for `karmadactl init` and `karmada operator` installation methods.

/help

**Comment by seanlaii** [comment]
Hi @XiShanYongYe-Chang , is there anyone working on the second task? I might be able to help with it.

**Comment by XiShanYongYe-Chang** [comment]
> Hi @XiShanYongYe-Chang , is there anyone working on the second task? I'm interested in working on it if needed.

Thanks~ @seanlaii, I will assign it to you!

**Comment by seanlaii** [comment]
I would like to clarify the requirement regarding the level of control for the `ImagePullPolicy` in Karmada Operator. Specifically, should we provide control at the resource level or the component level in the Karmada custom resource?

Currently, the Karmada Operator installs Karmada through a custom resource, [Karmada](https://github.com/karmada-io/karmada/blob/release-1.9/operator/config/samples/karmada.yaml). To address this requirement, I propose adding an `ImagePullPolicy` field to the [CommonSettins](https://github.com/karmada-io/karmada/blob/release-1.9/operator/pkg/apis/operator/v1alpha1/type.go#L518) field in Karmada custom resource. This approach would enable users to define individual pull policies for each component.
Could you please confirm if this approach aligns with the expected behavior? I appreciate your guidance on ensuring a proper implementation that meets the project's standards and requirements. 
Thanks for your time!

**Comment by XiShanYongYe-Chang** [comment]
Thanks @seanlaii 
All task pr has been merged.
/close

**Comment by seanlaii** [comment]
Thank you for your time! Btw, it is worth noting that we might need to upgrade the [controller-gen](https://github.com/karmada-io/karmada/blob/87c778247f5d3d29539901373fa0c5da3397c9ed/hack/update-crdgen.sh#L22) version to 0.14.0 when we upgrade Go version to v1.22 due to this [issue](https://github.com/kubernetes-sigs/controller-tools/issues/888). During my local development using Go v1.22, I encountered the same problem. However, after downgrading to Go v1.21.8, everything functioned as expected.

**Comment by XiShanYongYe-Chang** [comment]
Thanks for the reminder. If it's convenient, you can raise a new issue to track this. We need to do this when we upgrade the go version to 1.22.

**Comment by seanlaii** [comment]
Sure! I created it [here](https://github.com/karmada-io/karmada/issues/4873). Feel free to let me know if I need to add any tags or labels cause I am new to creating issues. Thanks!
