### ISSUE TITLE
member clusters can be join repeatedly

### ISSUE THREAD

**Issue by 2hangchen** [karmada-io/karmada#880]
The same member cluster can be joined to Karmada in two aliases(ClusterName),i don't know if this is a bug or by design?

**Environment**:
- Karmada version:0.9.0
- Others:

**Comment by mrlihanbo** [comment]
A cluster could be joined many times as long as with a different name. We can't identify the cluster by apiserver address because some clusters may have internal address and EIP for apiserver. 
When a cluster joined repeatedly, once you remove one of them, all of the clusters will turn into unready status. This happens because they share the same RBAC resources. The RBAC resources will be deleted when a cluster is unjoined. The same scenario will happen if a cluster is joined to different karmada instance at the same time.

**Comment by RainbowMango** [comment]
/close 
in favor of #2369
