### ISSUE TITLE
karmadactl cordon -h can't work correctly

### ISSUE THREAD

**Issue by Shike-Ada** [karmada-io/karmada#892]
**What happened**:
A function in /pkg/karmadactl/cordon.go called AddFlags(140 ~144lines) can't work correctly, because when I input "karmadactl cordon -h", as shown below, it just print one Flags called "-h". It doesn't make sense since I can't get any help by inputting this command.
![Karmada的bug1截图](https://user-images.githubusercontent.com/80157436/139574633-1c6b74cb-9233-4a60-a6ec-378d0de57175.PNG)
![Karmada的bug1截图2](https://user-images.githubusercontent.com/80157436/139574657-afbb69f6-f632-4df8-a353-5f3558dc919b.PNG)
**What you expected to happen**:
As a contrast, when I use"Karmadactl get -h", it print enough flags of information.
![image](https://user-images.githubusercontent.com/80157436/139574938-b8be6097-5917-4e44-9d8d-e455960c5aea.png)
**How to reproduce it (as minimally and precisely as possible)**:
Type "karmadactl cordon -h"

**Environment**:
- Karmada version:0.9.0
- Others:

**Comment by Garrybest** [comment]
The command `karmadactl cordon -h` does print the related information. See below.

```bash
$ karmadactl cordon -h
Mark cluster as unschedulable.

Usage:
  karmadactl cordon CLUSTER [flags]

Examples:

# Mark cluster "foo" as unschedulable.
karmadactl cordon foo


Flags:
  -h, --help   help for cordon
```

The action `cordon` does not need any other flags. The example `karmadactl cordon foo` does explain well.

**Comment by lonelyCZ** [comment]
There could be a omit in `cordon` and `uncordon`


The `AddFlags` has been defined, but is not used so that `--karmada-context` and `--dry-run` flags can not be input when executing `karmadactl cordon` or `karmadactl uncordon`.
https://github.com/karmada-io/karmada/blob/421bf6da0a10a0afc808e3107db9dd92d461e67e/pkg/karmadactl/cordon.go#L115-L120

# Solution
We should add following code in `NewCmdCordon` and `NewCmdUncordon`.
https://github.com/karmada-io/karmada/blob/421bf6da0a10a0afc808e3107db9dd92d461e67e/pkg/karmadactl/join.go#L84-L85
